"""Replace type column with ENUM AuxilliaryDataType

Revision ID: addbfd8346cd
Revises: 8a0ccfe5e66a
Create Date: 2025-04-01 22:57:22.980392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'addbfd8346cd'
down_revision: Union[str, None] = '8a0ccfe5e66a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auxilliary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('PROMPT', name='auxilliary_data_type'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_index(op.f('ix_auxilliary_id'), 'auxilliary', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auxilliary_id'), table_name='auxilliary')
    op.drop_table('auxilliary')
    # ### end Alembic commands ###
